# Generated by Django 4.2.1 on 2023-05-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_imagesmodel_work_example_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesmodel',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagesmodel',
            name='after_image',
            field=models.ImageField(upload_to='static/services/images/', verbose_name='Изображение после'),
        ),
        migrations.AlterField(
            model_name='imagesmodel',
            name='before_image',
            field=models.ImageField(upload_to='static/services/images/', verbose_name='Изображение до'),
        ),
        migrations.AlterField(
            model_name='workexamplemodel',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='workexamplemodel',
            name='end_date',
            field=models.DateTimeField(verbose_name='Дата окончания работы'),
        ),
        migrations.AlterField(
            model_name='workexamplemodel',
            name='images_id',
            field=models.ManyToManyField(to='services.imagesmodel', verbose_name='Фото работ'),
        ),
        migrations.AlterField(
            model_name='workexamplemodel',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата начала работы'),
        ),
    ]
