# Generated by Django 4.2.1 on 2023-05-07 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_imagesmodel_title_alter_imagesmodel_after_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagesmodel',
            options={'verbose_name': 'Изображения', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.RemoveField(
            model_name='workexamplemodel',
            name='images_id',
        ),
        migrations.AddField(
            model_name='imagesmodel',
            name='work_example_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.workexamplemodel', verbose_name='Фото работ'),
            preserve_default=False,
        ),
    ]
