# Generated by Django 4.2.1 on 2023-05-08 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_imagesmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesmodel',
            name='work_example_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_set', to='services.workexamplemodel', verbose_name='Фото работ'),
        ),
        migrations.AlterField(
            model_name='workexamplemodel',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания работы'),
        ),
        migrations.AlterField(
            model_name='workexamplemodel',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_examples_set', to='services.servicemodel'),
        ),
        migrations.AlterField(
            model_name='workexamplemodel',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала работы'),
        ),
    ]
